### PR TITLE
api98: TCK Challenge: TCK should not require JPMS module-info.class

### PR DESCRIPTION
**Pull request by lukasj**
this is supposed to address https://github.com/jakartaee/jaf-api/issues/98

@scottmarlow @brideck - review, please

### CODE REVIEW

**Review by brideck — CHANGES_REQUESTED** [review]
Thanks, Lukas. This largely looks good, just a few updates needed that I've commented on. With those changes, I've been able to run this against Open Liberty.

**Review by brideck — APPROVED** [review]

**Comment by scottmarlow** [comment]
passes locally for me also.  Thanks for the change @lukasj

**Review by scottmarlow — APPROVED** [review]

**Comment by brideck** [comment]
@lukasj Ach, I'm apparently an idiot. I must have verified these changes against an instance of Open Liberty with a modularized Activation API jar because this is **not** actually working for me out of the box with a clean OL install. It still needs a change similar to the one made for the Mail TCK (https://github.com/jakartaee/mail-tck/pull/51).

You can see the same `modulepath` on the JavaTest invocation -- https://github.com/jakartaee/jaf-tck/blob/master/build.xml#L225

**Comment by lukasj** [comment]
PR cannot be reopened, file new issue

**Comment by brideck** [comment]
I would reopen https://github.com/jakartaee/jaf-api/issues/98 myself, but I do not have the permission to. Please do so, and an additional PR can be attached to it.

**Pull request merged**
